### ISSUE TITLE
PowerShell wrapper issues - Get-OktaUser : Method not found: 'Okta.Core.EnumerableResults

### ISSUE THREAD

**Issue by hkelley** [okta/oktasdk-csharp#10]
I have installed the API but can't use the Get-OktaUser cmdlet.  I always get this response:

`Get-OktaUser : Method not found: 'Okta.Core.EnumerableResults`1<!0> Okta.Core.Clients.ApiClient`1.GetFilteredEnumerator(Okta.Core.FilterBuilder, Int32, System.String, System.String, System.Nullable`1<System.DateTime>)'.`

I used PowerShell to create .NET settings and client objects and then connected  so I don't think it's an issue with the 4.0 runtime.

` $client = New-Object Okta.Core.Clients.OktaClient($settings)`

**Comment by raphaellondner-okta** [comment]
Thank you for reporting this issue which I confirm. It has now been fixed in the latest version of the PowerShell package, which you can install by running the following chocolatey command:

`choco upgrade okta.core.automation -version 0.1.5.0`
