### ISSUE TITLE
Get-OktaUser : Error making an HTTP request: One or more errors occurred.

### ISSUE THREAD

**Issue by hkelley** [okta/oktasdk-csharp#11]
The Get-OktaUser cmdlet no longer retrieves all users.  It still works when I specify a single user.

The direct API still seems to work via curl.

`curl -v -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS %1" "https://%2.okta.com/api/v1/users/"`

This is the PS exception I get.  Has anyone else seen this?   

```
PS C:\temp> Get-OktaUser
Get-OktaUser : Error making an HTTP request: One or more errors occurred.
At line:1 char:1
+ Get-OktaUser
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-OktaUser], OktaException
    + FullyQualifiedErrorId : Okta.Core.OktaException,Okta.Core.Automation.Get
   OktaUser
```

**Comment by hkelley** [comment]
Could this be related to pagination?

[http://developer.okta.com/docs/api/getting_started/design_principles#pagination](url)

The Get-OktaUser cmdlet only stopped working after we activated a large batch of users (probably pushing us over the limit of 200).

**Comment by raphaellondner-okta** [comment]
This issue has been resolved with the latest version of the Okta PowerShell Module (v0.1.5.6) cf. https://chocolatey.org/packages/Okta.Core.Automation/0.1.5.6
