### ISSUE TITLE
UserClient.SetCredentials gives exception

### ISSUE THREAD

**Issue by sandernaert** [okta/oktasdk-csharp#15]
I get an exception when I try to use **UserClient.SetCredentials(string id, LoginCredentials credentials)**
It works when I pass in a user but not when i just pass in an Id.

It does a Put request to the wrong url and will always receive a 404 response.

I think **BaseClient.Put(id, userWithCredentials.ToJson());**
should be replaced with **BaseClient.Put(GetResourceUri(id), userWithCredentials.ToJson());**

**Comment by raphaellondner-okta** [comment]
Thank you for reporting the issue and for providing a fix! I've now fixed the source code as well as added a unit test for that method. The compiled assembly is also updated in NuGet now (v0.3.1.0).

Next time you identity an issue., don't hesitate to fork the repo into your own GitHub account and submit a pull request with a suggested fix.
