### ISSUE TITLE
change Constants from internal to public class

### ISSUE THREAD

**Issue by andyclarke-okta** [okta/oktasdk-csharp#24]
Allow custom applications to leverage declared constants in Okta.Core

namespace Okta.Core
{
    internal class Constants
    {

**Comment by jmelberg-okta** [comment]
@andyclarke-okta: This was updated in a previous commit. Please take a look at [Constants.cs#L7-L9](https://github.com/okta/oktasdk-csharp/blob/c66b2b9e7d8694745f34cc9347adb0806033d651/Okta.Core/Constants.cs#L7-L9)
