### ISSUE TITLE
chocolatey install user profile

### ISSUE THREAD

**Issue by hjmiii** [okta/oktasdk-csharp#4]
Ran into an issue on chocolatey install. A user's powershell profile isn't always rooted from the $home dir. The $profile variable might be better. Ex. CocolateyInstall.ps1 line 4
$folder = $profile.Substring(0,($profile.LastIndexOf("\"))) + "\Modules\$($packageName)"

**Comment by raphaellondner-okta** [comment]
Apologies for the late response. Can you verify this is still an open issue with the latest version of the PowerShell module? https://chocolatey.org/packages/Okta.Core.Automation/0.1.5.6
