### ISSUE TITLE
Client slow after 3 requests

### ISSUE THREAD

**Issue by michaelallenics** [okta/oktasdk-csharp#5]
I have a program that gets a list of my groups, then prints each group Id. The program runs quickly (~ 3 seconds) the first 3 times I run it, but after that it takes ~28 seconds to run. This only occurs if I am running the exe several times, if I put the code in a for loop and run it 10 times the first loop iteration takes ~28 seconds, then each subsequent iteration takes less than a second. 
My code:

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using OktaAPI;
    using Okta.Core;
    using Okta.Core.Clients;
    using Okta.Core.Models;

    namespace OktaAPIOut
    {
        class Program
        {
            static void Main(string[] args)
            {
                var oktaClient = new OktaClient("oktapikey", new Uri("myoktatenant"));

                var groupClient = oktaClient.GetGroupsClient();
                var groupList = groupClient.GetList();
                foreach (var group in groupList.Results)
                {
                    Console.WriteLine("group:" + group.Id);
                }
                Console.ReadKey();
            }
        }
    }

The issue is similar to this: http://stackoverflow.com/questions/28384438/net-httpclient-postasync-slow-after-3-requests

my .NET version is 4.0.30319

**Comment by raphaellondner-okta** [comment]
This is most likely due to our API rate limiting cf. https://support.okta.com/help/articles/Knowledge_Article/API-Rate-Limiting

I am closing this issue now since it's more than a year old (and likely not solved)
