### ISSUE TITLE
Is a simpler example available?

### ISSUE THREAD

**Issue by pipwerks** [okta/oktasdk-csharp#6]
This is not really an issue, more of a request: Can you please provide a simpler example for Okta in C#/ASP.Net that doesn't utilize the music store project?

Not being familiar with the music store project, I find myself spending a ton of time sifting through the code trying to determine where the Okta code resides. It's very confusing for a n00b like me.

My particular use case is a small intranet site locked down via web.config authentication, such as:

    <system.webServer>
        <security>
            <authorization>
                <remove users="*" roles="" verbs="" />
                <add accessType="Allow" users="" roles="Administrators" />
            </authorization>
        </security>
    </system.webServer>

Can you provide any examples for integrating Okta with this type of authentication?

Thanks!

**Comment by jpf** [comment]
For an intranet site, I would suggest implementing SSO via WS-Fed, then have Okta sign users on to your interanet site via WS-Fed. Instructions for [configuring WS-Fed in Okta](https://support.okta.com/articles/Knowledge_Article/29510977-Configuring-the-Okta-Template-WS-Federation-Application) are available on [support.okta.com](https://support.okta.com).

You can also have your intranet application use Okta to verify usernames and passwords, to do this, you can also use the Membership and Role providers from the Music Store to do that. You can see how I did this in the Music Store in [the commit where I added the OktaProviders to the music store](https://github.com/okta/okta-music-store/commit/c11886941d9c63d93f178d3629e90ec0f57e1541#diff-e72015176ecade13d87750681aa254e5R45).

**Comment by pipwerks** [comment]
Thanks for the guidance, I will give it a shot. :)
