### ISSUE TITLE
C# SDK build fails - missing source file

### ISSUE THREAD

**Issue by neiljthomson** [okta/oktasdk-csharp#7]
Error	511	Source file 'Serialization\AuthResponseSerializationTests.cs' could not be found	E:\data\GitHub\Okta.Core.Tests\CSC	Okta.Core.Tests

**Comment by cbarbara-okta** [comment]
this was just fixed in https://github.com/okta/oktasdk-csharp/commit/4c3eb7693281b1897cb17bf26863dafa4fc0d717
